insert into soulpatches(id, created_at, updated_at, author, description, name, no_servings)
values (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 0', 'description 0', 'name 0',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 1', 'description 1', 'name 1',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 2', 'description 2', 'name 2',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 3', 'description 3', 'name 3',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 4', 'description 4', 'name 4',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 5', 'description 5', 'name 5',
        0),
       (nextval('soulpatches_sequence'), current_timestamp, current_timestamp, 'author 6', 'description 6', 'name 6',
        0);

insert into spfiles (id, created_at, updated_at, filetype, content, name, soulpatch_id)
VALUES (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOUL', 'soulfile content 0', 'soulfile 0',
        (select id from soulpatches where name = 'name 0')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOULPATCH', 'soulpatchfile content 0',
        'soulpatchfile 0',
        (select id from soulpatches where name = 'name 0')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOUL', 'soulfile content 1', 'soulfile 1',
        (select id from soulpatches where name = 'name 1')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOULPATCH', 'soulpatchfile content 1',
        'soulpatchfile 1',
        (select id from soulpatches where name = 'name 1')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOUL', 'soulfile content 2', 'soulfile 2',
        (select id from soulpatches where name = 'name 2')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOULPATCH', 'soulpatchfile content 2',
        'soulpatchfile 2',
        (select id from soulpatches where name = 'name 2')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOUL', 'soulfile content 3', 'soulfile 3',
        (select id from soulpatches where name = 'name 3')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOULPATCH', 'soulpatchfile content 3',
        'soulpatchfile 3',
        (select id from soulpatches where name = 'name 3')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOUL', 'soulfile content 4', 'soulfile 4',
        (select id from soulpatches where name = 'name 4')),
       (nextval('spfiles_sequence'), current_timestamp, current_timestamp, 'SOULPATCH', 'soulpatchfile content 4',
        'soulpatchfile 4',
        (select id from soulpatches where name = 'name 4'));

